# Generated by Django 4.2.1 on 2023-06-18 11:00

from django.db import migrations, models
import exercise.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prewritten_code', models.TextField()),
                ('preview_img', models.ImageField(default=exercise.models.get_default_image, upload_to='images/')),
                ('answer', models.TextField()),
            ],
        ),
    ]
