# Generated by Django 4.2.1 on 2023-08-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
