# Generated by Django 4.2.1 on 2023-08-17 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='project.project'),
        ),
    ]
