# Generated by Django 4.2.1 on 2023-08-17 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_section_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.image'),
        ),
    ]
