# Generated by Django 4.2.1 on 2023-06-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduboost', '0002_alter_course_title_alter_lesson_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
