# Generated by Django 4.2.1 on 2023-06-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduboost', '0003_course_is_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_popular',
            new_name='is_featured',
        ),
    ]
