# Generated by Django 4.2.1 on 2023-08-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduboost', '0004_rename_is_popular_course_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='course', max_length=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='lesson', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='video', max_length=30),
        ),
    ]
